service: number-plates-detection-demo

frameworkVersion: '3'

custom:
  wsgi:
    app: app.app

provider:
  name: aws
  runtime: python3.9
  stage: prod
  region: ap-northeast-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:ListBucket"
        - "s3:GetObject"
        - "s3:PutObject"
        - "s3:DeleteObject"
      Resource:
        - "*"
  environment:
    BUCKET: ${self:service}-${self:provider.stage}
    REGION: ${self:provider.region}

resources:
  Resources:
    Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:provider.environment.BUCKET}
        LifecycleConfiguration:
          Rules:
            - Status: Enabled
              ExpirationInDays: 1
        PublicAccessBlockConfiguration:
          BlockPublicAcls: true
          IgnorePublicAcls: true
          BlockPublicPolicy: false
          RestrictPublicBuckets: true

    DetectInputBucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket:
          Ref: Bucket
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action: s3:GetObject
              Resource:
                Fn::Sub: ${Bucket.Arn}/*
              Principal: "*"

layers:
  python-app-dependencies:
    path: layers/tools
    compatibleRuntimes:
      - python3.9
    description: "Dependencies open-cv for python functions"

functions:
  api:
    handler: wsgi_handler.handler
    # layers:
    #   - "${cf:number-plates-detection-demo-prod.PythonDashappDashdependenciesLambdaLayerQualifiedArn}"
    events:
      - httpApi: '*'

plugins:
  - serverless-wsgi
  - serverless-python-requirements

package:
  exclude:
    - README.md
    - node_modules/**
    - venv/**